name: jflex
URL: https://github.com/jflex-de/jflex.git
checkoutID: e6d1752bd48a7ccb2a2b78479dc5a73ac475bbb9
patchName: artifacts/configs/jflex/jflex.patch
subProject: jflex
#mvnOptions: -DfailIfNoTests=false -Dmaven.surefire.debug="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000"
mvnOptions: -DfailIfNoTests=false
properties:
  # - name: StateSetQuickcheck#size2nbits
  #   entryPoint: "jflex.state.StateSetQuickcheck.size2nbits(I)V"
  # - name: StateSetQuickcheck#containsIsSubset
  #   entryPoint: "jflex.state.StateSetQuickcheck.containsIsSubset(Ljflex/state/StateSet;Ljflex/state/StateSet;)V"
  # - name: StateSetQuickcheck#addIsUnion
  #   entryPoint: "jflex.state.StateSetQuickcheck.addIsUnion(Ljflex/state/StateSet;Ljflex/state/StateSet;)V"
  # - name: StateSetQuickcheck#addCommutes
  #   entryPoint: "jflex.state.StateSetQuickcheck.addCommutes(Ljflex/state/StateSet;Ljflex/state/StateSet;)V"
  # - name: StateSetQuickcheck#addEmpty
  #   entryPoint: "jflex.state.StateSetQuickcheck.addEmpty(Ljflex/state/StateSet;)V"
  # - name: StateSetQuickcheck#addSelf
  #   entryPoint: "jflex.state.StateSetQuickcheck.addSelf(Ljflex/state/StateSet;)V"
  # - name: StateSetQuickcheck#addIdemPotent
  #   entryPoint: "jflex.state.StateSetQuickcheck.addIdemPotent(Ljflex/state/StateSet;Ljflex/state/StateSet;)V"
  # - name: StateSetQuickcheck#intersect
  #   entryPoint: "jflex.state.StateSetQuickcheck.intersect(Ljflex/state/StateSet;Ljflex/state/StateSet;)V"
  # - name: StateSetQuickcheck#intersectUnchanged
  #   entryPoint: "jflex.state.StateSetQuickcheck.intersectUnchanged(Ljflex/state/StateSet;Ljflex/state/StateSet;)V"
  # - name: StateSetQuickcheck#intersectCommutes
  #   entryPoint: "jflex.state.StateSetQuickcheck.intersectCommutes(Ljflex/state/StateSet;Ljflex/state/StateSet;)V"
  # - name: StateSetQuickcheck#intersectEmpty
  #   entryPoint: "jflex.state.StateSetQuickcheck.intersectEmpty(Ljflex/state/StateSet;)V"
  # - name: StateSetQuickcheck#intersectSelf
  #   entryPoint: "jflex.state.StateSetQuickcheck.intersectSelf(Ljflex/state/StateSet;)V"
  # - name: StateSetQuickcheck#containsItsElements
  #   entryPoint: "jflex.state.StateSetQuickcheck.containsItsElements(Ljflex/state/StateSet;)V"
  # - name: StateSetQuickcheck#removeRemoves
  #   entryPoint: "jflex.state.StateSetQuickcheck.removeRemoves(Ljflex/state/StateSet;I)V"
  - name: StateSetQuickcheck#removeAdd
    entryPoint: "jflex.state.StateSetQuickcheck.removeAdd(Ljflex/state/StateSet;I)V"
  # - name: StateSetQuickcheck#clearMakesEmpty
  #   entryPoint: "jflex.state.StateSetQuickcheck.clearMakesEmpty(Ljflex/state/StateSet;)V"
  # - name: StateSetQuickcheck#addStateAdds
  #   entryPoint: "jflex.state.StateSetQuickcheck.addStateAdds(Ljflex/state/StateSet;I)V"
  # - name: StateSetQuickcheck#addStateDoesNotRemove
  #   entryPoint: "jflex.state.StateSetQuickcheck.addStateDoesNotRemove(Ljflex/state/StateSet;I)V"
  # - name: StateSetQuickcheck#addStateAdd
  #   entryPoint: "jflex.state.StateSetQuickcheck.addStateAdd(Ljflex/state/StateSet;I)V"
  # - name: StateSetQuickcheck#complementNoOriginalElements
  #   entryPoint: "jflex.state.StateSetQuickcheck.complementNoOriginalElements(Ljflex/state/StateSet;Ljflex/state/StateSet;)V"
  # - name: StateSetQuickcheck#complementElements
  #   entryPoint: "jflex.state.StateSetQuickcheck.complementElements(Ljflex/state/StateSet;Ljflex/state/StateSet;)V"
  # - name: StateSetQuickcheck#complementUnion
  #   entryPoint: "jflex.state.StateSetQuickcheck.complementUnion(Ljflex/state/StateSet;Ljflex/state/StateSet;)V"
  # - name: StateSetQuickcheck#containsElements
  #   entryPoint: "jflex.state.StateSetQuickcheck.containsElements(Ljflex/state/StateSet;I)V"
  # - name: StateSetQuickcheck#containsNoElements
  #   entryPoint: "jflex.state.StateSetQuickcheck.containsNoElements(Ljflex/state/StateSet;)V"
  # - name: StateSetQuickcheck#copy
  #   entryPoint: "jflex.state.StateSetQuickcheck.copy(Ljflex/state/StateSet;)V"
  # - name: StateSetQuickcheck#copyInto
  #   entryPoint: "jflex.state.StateSetQuickcheck.copyInto(Ljflex/state/StateSet;Ljflex/state/StateSet;)V"
  # - name: StateSetQuickcheck#hashCode
  #   entryPoint: "jflex.state.StateSetQuickcheck.hashCode(Ljflex/state/StateSet;Ljflex/state/StateSet;)V"
  # - name: StateSetQuickcheck#getAndRemoveRemoves
  #   entryPoint: "jflex.state.StateSetQuickcheck.getAndRemoveRemoves(Ljflex/state/StateSet;)V"
  # - name: StateSetQuickcheck#getAndRemoveIsElement
  #   entryPoint: "jflex.state.StateSetQuickcheck.getAndRemoveIsElement(Ljflex/state/StateSet;)V"
  # - name: StateSetQuickcheck#getAndRemoveAdd
  #   entryPoint: "jflex.state.StateSetQuickcheck.getAndRemoveAdd(Ljflex/state/StateSet;)V"
  # - name: StateSetQuickcheck#enumerator
  #   entryPoint: "jflex.state.StateSetQuickcheck.enumerator(Ljflex/state/StateSet;)V"
