name: mph-table
URL: https://github.com/indeedeng/mph-table.git
checkoutID: dbd5413df33bf8f0a995822eeefe94df50f3c5a7
patchName: artifacts/configs/mph-table/mph-table.patch
properties:
  - name: TestSmartListSerializer#canRoundTripSerializableLists
    entryPoint: "com.indeed.mph.serializers.TestSmartListSerializer.canRoundTripSerializableLists(Ljava/util/List;Ljava/util/List;Ljava/util/List;)V"
  - name: TestSmartListSerializer#canRoundTripSerializableListsWithGenerator
    entryPoint: "com.indeed.mph.serializers.TestSmartListSerializer.canRoundTripSerializableListsWithGenerator(Ljava/util/List;Ljava/util/List;Ljava/util/List;)V"