name: datasonnet-mapper
URL: https://github.com/datasonnet/datasonnet-mapper.git
checkoutID: 2.5
patchName: artifacts/configs/datasonnet-mapper/datasonnet-mapper.patch
mainJar: datasonnet-mapper-2.5-jar-with-dependencies.jar
testJar: datasonnet-mapper-2.5-tests.jar
properties:
  - name: